### ISSUE TITLE
Add Blazing Emerald and Brilliant Diamond Runmons

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/pbr-movesets#63]
Also investigate RandoBlack, RandoBlack2 and Spaceworld

**Comment by Torq-A** [comment]
I previously logged some of the RandoBlack, RandoBlack2, and Blazing Runmons, but I removed them because the moveset team said they were working on it too. They’re still in the runmons update if you want to use them as reference, though I had to replace some of the moves and abilities due to PBR not having them

**Comment by Torq-A** [comment]
Added these all into the BDSP pull.

**Comment by Torq-A** [comment]
Current pull updated with all runmons up to this point (only thing I’m missing is the EVs for rerandomized Sanqui, but that’s it). Let me know if there are any more issues before it can be added

**Comment by Torq-A** [comment]
This was implemented, so this can be safely closed
